"""Create initial user, patient, and vitals tables
...
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '078cdab52bb8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - PLEASE ADJUST! ###
    
    # 1. CREATE USER TABLE FIRST (Mandatory: Patient table depends on this)
    op.create_table('user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=80), nullable=False),
        sa.Column('password_hash', sa.String(length=128), nullable=False),
        sa.Column('role', sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username')
    )
    
    # 2. CREATE PATIENT TABLE (References user, so must be second)
    op.create_table('patient',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('age', sa.Integer(), nullable=True),
        sa.Column('gender', sa.String(length=10), nullable=True),
        sa.Column('location', sa.String(length=50), nullable=True),
        sa.Column('is_pregnant', sa.Boolean(), nullable=True),
        sa.Column('pregnancy_week', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id')
    )
    
    # 3. CREATE CONSULTATION TABLE (References patient)
    op.create_table('consultation',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('patient_id', sa.Integer(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.Column('doctor_name', sa.String(length=100), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('alert_level', sa.String(length=20), nullable=True),
        sa.Column('escalated_by', sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # 4. CREATE VITALS RECORD TABLE (References patient)
    op.create_table('vitals_record',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('patient_id', sa.Integer(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.Column('heart_rate', sa.String(length=20), nullable=True),
        sa.Column('blood_pressure', sa.String(length=20), nullable=True),
        sa.Column('spo2', sa.String(length=20), nullable=True),
        sa.Column('temperature', sa.String(length=20), nullable=True),
        sa.Column('ecg_status', sa.String(length=50), nullable=True),
        sa.Column('cortisol', sa.String(length=20), nullable=True),
        sa.Column('estrogen', sa.String(length=20), nullable=True),
        sa.Column('progesterone', sa.String(length=20), nullable=True),
        sa.Column('testosterone', sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # 5. Drop old tables (safely ignore if they don't exist in the new DB)
    op.drop_table('vitals', if_exists=True)
    op.drop_table('symptom', if_exists=True)
    # ### end Alembic commands ###


def downgrade():
    # ... (downgrade functions can remain as is)
    op.create_table('symptom',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('symptom', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vitals',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('heartRate', sa.VARCHAR(length=20), nullable=True),
    sa.Column('bloodPressure', sa.VARCHAR(length=20), nullable=True),
    sa.Column('spo2', sa.VARCHAR(length=20), nullable=True),
    sa.Column('temperature', sa.VARCHAR(length=20), nullable=True),
    sa.Column('ecgStatus', sa.VARCHAR(length=50), nullable=True),
    sa.Column('cortisol', sa.VARCHAR(length=20), nullable=True),
    sa.Column('estrogen', sa.VARCHAR(length=20), nullable=True),
    sa.Column('progesterone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('testosterone', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('vitals_record')
    op.drop_table('consultation')
    op.drop_table('patient')
    # ### end Alembic commands ###