"""Finalizing registration schema

Revision ID: 208f3fffb4f8
Revises: 7a2ef8905bd8
Create Date: 2025-10-17 01:35:10.603313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '208f3fffb4f8'
down_revision = '7a2ef8905bd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guardian_phone', sa.String(length=30), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guardian_phone', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('guardian_phone')

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('guardian_phone')

    # ### end Alembic commands ###
