"""Cleanup duplicated columns from User table

Revision ID: 7467e7a4d650
Revises: 208f3fffb4f8
Create Date: 2025-10-17 01:54:56.611700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7467e7a4d650'
down_revision = '208f3fffb4f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('guardian_phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guardian_phone', sa.VARCHAR(length=30), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
